theme: jekyll-theme-cayman
title: [Seeing Voices and Hearing Faces: Cross-modal biometric matching]
description: [Given an audio clip and two or more faces, decide which face would produce the audio clip]